src/objects/Admin__c.object
<CustomObject>
    <fields>
        <fullName>CourseTraier__c</fullName>
        <label>CourseTraier</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Janelle</fullName>
                </value>
                <value>
                    <fullName>jhon</fullName>
                </value>
                <value>
                    <fullName>Joe</fullName>
                </value>
                <value>
                    <fullName>Rayan</fullName>
                </value>
                <value>
                    <fullName>Tim</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Admin</label>
    <nameField>
        <label>Admin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admin</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SinglepicklistforMyAccount.cls
public class SinglepicklistforMyAccount

{

    public SinglepicklistforMyAccount() {

    }


    
    public SinglepicklistforMyAccount(ApexPages.StandardController controller) {

    }


    public string selectedValue { get;set; }

    public List<SelectOption> statusOptions { get;set; }

     

    public void autoRun()

    {

        Schema.DescribeFieldResult statusFieldDescription = Admin__c.CourseTraier__c.getDescribe();

        statusOptions = new list<SelectOption>();

         

        for (Schema.Picklistentry picklistEntry : statusFieldDescription.getPicklistValues())

      {

            statusOptions.add(new SelectOption(pickListEntry.getValue(),pickListEntry.getLabel()));

        }

    
    }
    

 

    public void checkValue()

    {

        System.debug('----------------'+selectedValue);

    }
    }