src/objects/Admin__c.object
<CustomObject>
    <fields>
        <fullName>CourseTraier__c</fullName>
        <label>CourseTraier</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Janelle</fullName>
                </value>
                <value>
                    <fullName>jhon</fullName>
                </value>
                <value>
                    <fullName>Joe</fullName>
                </value>
                <value>
                    <fullName>Rayan</fullName>
                </value>
                <value>
                    <fullName>Tim</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Courses_admin__c</fullName>
        <label>Courses_admin</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Admin 101</fullName>
                </value>
                <value>
                    <fullName>Admin 102</fullName>
                </value>
                <value>
                    <fullName>Admin 103</fullName>
                </value>
                <value>
                    <fullName>Admin 104</fullName>
                </value>
                <value>
                    <fullName>Admin 105</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Admin</label>
    <nameField>
        <label>Admin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admin</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GetSerciceOfInterestOptionList.cls
public class GetSerciceOfInterestOptionList{
public Admin__c adminRecord;


    public GetSerciceOfInterestOptionList(ApexPages.StandardController controller) {
    adminRecord=(Admin__c)controller.getRecord();

    }

public List<SelectOption> tempOptionLst;

public List<SelectOption> getSerciceOfInterestOptionList(){
    tempOptionLst = new List<SelectOption>();
    Schema.DescribeFieldResult rst5 = Admin__c.Courses_admin__c.getDescribe();
    List<Schema.PickListEntry> lst5 = rst5.getPickListValues();
    tempOptionLst.add(new SelectOption('','None'));
    for(Schema.PickListEntry obj:lst5){
        tempOptionLst.add(new SelectOption(obj.getLabel(),obj.getValue()));
    }
    return tempOptionLst;
 }
 public List<SelectOption> tempOptions2;
 public List<SelectOption> getTrainerList(){
    tempOptions2= new List<SelectOption>();
    Schema.DescribeFieldResult rst5 = Admin__c.CourseTraier__c.getDescribe();
    List<Schema.PickListEntry> lst5 = rst5.getPickListValues();
    tempOptions2.add(new SelectOption('','None'));
    for(Schema.PickListEntry obj:lst5){
        tempOptions2.add(new SelectOption(obj.getLabel(),obj.getValue()));
    }
    return tempOptions2;
 }
 public   PageReference save(){ 

insert adminRecord;

PageReference pg=new PageReference('/apex/PageConfirmation');

pg.setRedirect(true);

return pg;
}

public PageReference cancel(){

PageReference pg=new PageReference('/a09/o');
pg.setRedirect(true);
return pg;
}
}